openapi: 3.0.0
info:
  title: user api
  version: "1.0"
  description: "The user API of Greenstand for user/custom service"
  contact:
    name: Greenstand User API
    url: "https://[env].treetracker.org/user-api"
servers:
  - url: "http://[env].treetracker.org/user-api"
paths:
  "/register":
    parameters:
      - name: body
        in: body
        required: true
        schema:
          $ref: "#/components/schemas/user"
    post:
      summary: Register a new user
      operationId: registerUser
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/user"
  "/gift-token":
    post:
      summary: Send a gift token to a user by email
      operationId: giftToken
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
              tokenId:
                type: string
      responses:
        "200":
          description: OK
    get:
      summary: Get all gift token sent by me
      operationId: getGiftToken
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    email:
                      type: string
                    tokenId:
                      type: string
                    createdAt:
                      type: string
                      format: date-time

components:
  schemas:
    user:
      type: object
      properties:
        username:
          type: string
        email:
          type: string
        password:
          type: string
        phone:
          type: string
