apiVersion: apps/v1
kind: Deployment
metadata:
  name: treetrackerwallet-webapp
spec:
  selector:
    matchLabels:
      app: treetrackerwallet-webapp
  replicas: 1
  template:
    metadata:
      labels:
        app: treetrackerwallet-webapp
    spec:
      containers:
      - name: treetrackerwallet-webapp
        image: registry.github.com/Greenstand/treetracker-wallet-app/snapshot
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: git-token
---
apiVersion: v1
kind: Service
metadata:
  name: treetrackerwallet-webapp
spec:
  type: ClusterIP
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: treetrackerwallet-webapp
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: treetrackerwallet-webapp-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    # Optional: nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: treetrackerwallet.example.com
    http:
      paths:
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: treetrackerwallet-webapp
            port:
              number: 3000
  # Optional: TLS
  # tls:
  # - hosts:
  #     - treetrackerwallet.example.com
  #   secretName: treetrackerwallet-tls