apiVersion: apps/v1
kind: Deployment
metadata:
  name: treetracker-wallet-monorepo-user-api
  labels:
    app: treetracker-wallet-monorepo-user-api
  namespace: treetracker-wallet-monorepo-user-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: treetracker-wallet-monorepo-user-api
  template:
    metadata:
      labels:
        app: treetracker-wallet-monorepo-user-api
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: doks.digitalocean.com/node-pool
                    operator: In
                    values:
                      - microservices-node-pool
      containers:
        - name: treetracker-wallet-monorepo-user-api
          image: greenstand/treetracker-wallet-monorepo-user-api:TAG
          # get this from env as well
          ports:
            - containerPort: 8080
          env:
            - name: PRIVATE_KEYCLOAK_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: keycloak-connection
                  key: PRIVATE_KEYCLOAK_BASE_URL
            - name: PRIVATE_KEYCLOAK_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: keycloak-connection
                  key: PRIVATE_KEYCLOAK_CLIENT_ID
            - name: PRIVATE_KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: keycloak-connection
                  key: PRIVATE_KEYCLOAK_CLIENT_SECRET
            - name: PRIVATE_KEYCLOAK_REALM
              valueFrom:
                secretKeyRef:
                  name: keycloak-connection
                  key: PRIVATE_KEYCLOAK_REALM