apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-connection
  namespace: treetracker-wallet-monorepo-user-api
spec:
  encryptedData:
    PRIVATE_KEYCLOAK_BASE_URL: PLACEHOLDER
    PRIVATE_KEYCLOAK_CLIENT_ID: PLACEHOLDER
    PRIVATE_KEYCLOAK_CLIENT_SECRET: PLACEHOLDER
    PRIVATE_KEYCLOAK_REALM: PLACEHOLDER
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-connection
      namespace: treetracker-wallet-monorepo-user-api
