apiVersion: v1
kind: Service
metadata:
  name: treetracker-wallet-monorepo-user-api-service
  namespace: treetracker-wallet-monorepo-user-api
spec:
  selector:
    app: treetracker-wallet-monorepo-user-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
