apiVersion: batch/v1
kind: Job
metadata:
  name: database-migration-job
spec:
  backoffLimit: 1 # allow for one re-try of the migration
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: doks.digitalocean.com/node-pool
                operator: In
                values:
                - microservices-node-pool
      containers:
      - name: migration
        image: greenstand/treetracker-api:TAG
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: database-migration-connection
                key: db
        command: ["node"]
        args: ["node_modules/db-migrate/bin/db-migrate", "up", "--migrations-dir", "database/migrations/", "-v"]
      restartPolicy: Never
