name: CI for New Pull Requests

on:
  pull_request:
    branches:
      - "*"
    paths:
      - "apps/user/**" # Only trigger for changes in the apps/user directory

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      # Corepack will activate the Yarn version from the repo's packageManager field
      - name: Enable Corepack
        run: corepack enable

      # Prefer root install so workspaces resolve correctly with Berry
      - name: Install dependencies
        run: yarn install --immutable

      # For speed up, focus the user workspace:
      # - name: Focus user workspace
      #   run: yarn workspaces focus user --all

      - name: Build TypeScript project
        run: yarn workspace user build

      - name: Lint code with ESLint
        run: yarn workspace user lint

      - name: Run unit tests
        run: yarn workspace user test:unit

      - name: Run integration tests
        run: yarn workspace user int-test
